plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.guvensahin.coffeedictionary'
    compileSdk 35

    defaultConfig {
        applicationId "com.guvensahin.coffeedictionary"
        minSdk 21
        targetSdk 35
        versionCode 22
        versionName "1.2.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            resValue "string", "ADMOB_BANNER_ID", getProps("ADMOB_BANNER_ID")
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            resValue "string", "ADMOB_BANNER_ID", getProps("ADMOB_BANNER_ID")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.9.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.google.android.gms:play-services-ads:22.2.0'
    implementation 'com.google.firebase:firebase-analytics:21.3.0'
    implementation 'io.github.medyo:android-about-page:2.0.0'
    implementation files('libs/opencsv-4.2.jar')
    implementation 'org.apache.commons:commons-lang3:3.8'
}

def getProps(String propName) {
    def propsFile = rootProject.file('app/src/main/assets/config.properties')
    if (propsFile.exists()) {
        def props = new Properties()
        propsFile.withInputStream { props.load(it) }
        return props[propName] ?: ""
    } else {
        return ""
    }
}
